#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, 
#the first 10 terms will be:
# 1,2,3,5,8,13,21,34,55,89
#By considering the terms in the Fibonacci sequence whose values do not exceed N, find the sum of the even-valued terms

#Input Format
#First line contains 'T' that denotes the number of test cases. This is followed by  lines, each containing an integer, N.

#Constraints
# 1 <= T <= 10^5
# 1 <= N <= 4 * 10^6

#Output Format
#For each test case, print the answer.

setwd('S://DATA Science//R//HackerRank/')
getwd()

rm(list=ls())

take_input <- function(){
  t <- as.integer(readline())
  n <- NA
  if(t < 1 | t > 10^5){
    cat('T between 1 and 10^5 is permitted \n')
  }else{
    for(i in 1:t){
      n[i] <- as.integer(readline())
    }
  }
  return(n)
}

check_input <- function(vals){
  for(i in 1:length(vals))
  if(vals[i]<1 | vals[i] > 4 * 10^6){
    cat('N between 1 and 4 * 10^6 is permitted \n')
    return(FALSE)
  }else{
    return(TRUE) 
  }
}


print_fibo_Even_sum <- function(num){
  fibo <- NA
  fibo[1] <- 0
  fibo[2] <- 1
  for(j in 3:num){
    fibo[j] <- fibo[j-1] + fibo[j-2]
  }
  cat(sum(fibo[fibo%%2==0 & fibo < num]),'\n')
}  

values <- take_input()
flag_val <- check_input(values)
if(flag_val){
  for(i in 1:length(values)){
    print_fibo_Even_sum(as.numeric(values[i]))  
  }
}
  


